apps/product/urls.py
from django.urls import path
from product.views import UploadProducts, ExportProductsToXlsx, \
    UploadProductAspects, ExportProductAspectToXlsx, UploadAggregationModelSet, \
    ExportAggregationModelSet

app_name = 'product'
urlpatterns = [
    path('upload/', UploadProducts.as_view(), name="upload_product"),
    path('download-products/', ExportProductsToXlsx.as_view(), name="download_products"),
    path('aspect-upload/', UploadProductAspects.as_view(), name="upload_product_aspects"),
    path('download-aspects/', ExportProductAspectToXlsx.as_view(), name="download_product_aspects"),
    path('aggregation-model-set/', UploadAggregationModelSet.as_view(), name="upload_aggregation_model_set"),
    path('download-aggregation-model-set/', ExportAggregationModelSet.as_view(), name="download_aggregation_model_set"),
]

my_roga/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from my_roga import settings

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('', include(('home.urls'), namespace='home')),
    path('auth/', include(('authentication.urls'), namespace='authentication')),
    path('model-catalog/', include(('model_catalog.urls'), namespace='model_catalog')),
    path('product/', include(('product.urls'), namespace='product')),
    path('quiz/', include(('quiz.urls'), namespace='quiz')),
    path('admin/', admin.site.urls),
]

my_roga/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class ActivityTracking(models.Model):
    active = models.BooleanField(verbose_name=_('Active'), default=True)
    is_deleted = models.BooleanField(verbose_name=_('Is Deleted'), default=False)
    created_at = models.DateTimeField(verbose_name=_('Created At'),
                    auto_now_add=True, help_text=_("Date when created."), null=True)
    updated_at = models.DateTimeField(verbose_name=_('Updated At'),
                    auto_now=True, help_text=_("Date when updated."), null=True)
    deleted_at = models.DateTimeField(verbose_name=_('Deleted At'),
                    default=None, null=True, blank=True, help_text=_("Date when deleted"))
    delete_reason = models.CharField(max_length=300, verbose_name=_('Delete Reason'),
                    default=None, null=True, blank=True, help_text=_("Delete Reason"))

    class Meta:
        abstract = True

apps/product/views.py
import logging
import copy
import numpy as np
from django.utils import timezone
from django.shortcuts import render, redirect
from django.views import View
from openpyxl import Workbook
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin

from product.models import ProductCatalog, AspectsMetaData, AspectValuesMetaData, \
    AggregationModelSet
from home.models import MyRogaCategory, Language, MarketPlace
from my_roga.common.utils import read_file, VALID_FILE_EXTENSION, MODULES_NAME
from my_roga.common.actions import Actions
from my_roga.common.logs import LogAction
from product.common import get_formatted_products
from model_catalog.views import create_model_catalog, update_model_catalog


logger = logging.getLogger(__name__)


class UploadProducts(LoginRequiredMixin, View):
    template_name = "product/product.html"

    def get(self, request):
        selected_category = request.GET['category'] if 'category' in request.GET else None
        selected_product = request.GET['product'] if 'product' in request.GET else None

        categories = MyRogaCategory.objects.isNotDeleted()
        products = ProductCatalog.objects.isNotDeleted()

        # Get Product Columns dynamically and its value
        response = get_formatted_products(categories, products, selected_category, selected_product)

        COLUMNS = response['COLUMNS']
        results = response['results']
        selected_product = response["selected_product"]
        selected_category = response["selected_category"]
        return render(request, template_name=self.template_name, context={
            "error": False,
            "message": "Product(s) fetched Successfully!",
            "records": results,
            "categories": categories,
            "products": products,
            "selected_category": selected_category,
            "selected_product": selected_product,
            "categories": categories,
            "columns": COLUMNS,
        })

    def add_technical_aspect(self, **kwargs):
        TECHNICAL_ASPECTS_VALID_COLUMNS = kwargs['TECHNICAL_ASPECTS_VALID_COLUMNS']
        product = kwargs['product']
        product_catalog = kwargs['product_catalog']
        category = kwargs['category']
        for key, value in product.items():
            # Check if field is available in technical aspect
            if key in TECHNICAL_ASPECTS_VALID_COLUMNS:
                technical_aspect = AspectsMetaData.objects.filter(name__iexact=key, my_roga_category=category).first()
                product_catalog.technical_aspects.add(technical_aspect)

                if AspectValuesMetaData.objects.filter(
                        aspect_meta_data=technical_aspect,
                        my_roga_category=category,
                        value_name=product[key]).exists():

                    technical_aspect_value = AspectValuesMetaData.objects.filter(
                                                aspect_meta_data=technical_aspect,
                                                my_roga_category=category,
                                                value_name=product[key]).first()
                else:
                    technical_aspect_value = AspectValuesMetaData.objects.create(
                        aspect_meta_data = technical_aspect,
                        my_roga_category = category,
                        value_name = product[key],
                        value_type = '1' # 1 - Text
                    ) # TODO value_type needs to deside - Currently set it to TEXT
                product_catalog.technical_aspect_values.add(technical_aspect_value)
        product_catalog.save()
        return product_catalog
    
    def check_valid_product_technical_aspect(self, **kwargs):
        isValidTechnicalAspect = True
        TECHNICAL_ASPECTS_VALID_COLUMNS = kwargs['TECHNICAL_ASPECTS_VALID_COLUMNS']
        product = kwargs['product']
        category = kwargs['category']
        notValidTechnicalAspects = []
        for key, value in product.items():
            if key in TECHNICAL_ASPECTS_VALID_COLUMNS:
                technical_aspect = AspectsMetaData.objects.filter(name__iexact=key, my_roga_category=category).first()
                if not technical_aspect:
                    isValidTechnicalAspect = False
                    notValidTechnicalAspects.append(key)
        
        if not isValidTechnicalAspect:
            logger.error(f"{','.join(notValidTechnicalAspects)} - Technical Aspect with Category {category.id} not exist!")
            LogAction(MODULES_NAME['PRODUCT']).create('ERROR',
                f"{','.join(notValidTechnicalAspects)} - Technical Aspect with Category {category.id} not exist!")
            return False

        return True
    
    def post(self, request):
        VALID_COLUMNS = ['category', 'language', 'hero offer', 'second offer', \
            'title', 'description', 'product status', 'product stealth', \
            'action', 'product id', 'image url', 'review url', 'reviews count', 'reviews score', \
            'hero offer url', 'hero offer price', 'hero offer marketplace id', \
            'second offer url', 'second offer price', 'second offer marketplace id']

        PRODUCT_TECHNICAL_ASPECTS = list(AspectsMetaData.objects.values_list('name', flat=True))
        TECHNICAL_ASPECTS_VALID_COLUMNS = [ aspect.lower() for aspect in PRODUCT_TECHNICAL_ASPECTS]

        VALID_COLIMNS =  VALID_COLUMNS + TECHNICAL_ASPECTS_VALID_COLUMNS

        upload_file = request.FILES.get("upload_file")
        file_extension = upload_file.name.split(".")[1]
        isAllColumnsValid = True

        # Check valid file extension
        if file_extension not in VALID_FILE_EXTENSION:
            logger.error("Please Upload file with only xls, xlsx & csv extension!")
            return render(request, template_name=self.template_name, context={
                "error": True,
                "message": "Please Upload file with only xls, xlsx & csv extension!"
            })

        # Read the uploaded file
        try:
            products = read_file(upload_file)
        except Exception as e:
            logger.error(f"File not valid or does not have valid data! - {e.message}")
            return render(request, template_name=self.template_name, context={
                "error": True,
                "message": "File not valid or does not have valid data!"
            })
        
        # Uploaded file column names & Verify if it is valid
        file_columns =  list(map(lambda x:x.lower(), list(products.columns)))

        isAllColumnsValid = True
        for col in file_columns:
            if col not in VALID_COLIMNS:
                isAllColumnsValid = False
                break
        
        if not isAllColumnsValid:
            logger.error("Uploaded file does not have valid column names!")
            return render(request, template_name=self.template_name, context={
                "error": True,
                "message": "Uploaded file does not have valid column names!"
            })
        
        products.columns = file_columns
        # Replace nan to blank string
        products = products.replace(np.nan, '', regex=True)
        products = products.to_dict('records')

        for product in products:
            if not MyRogaCategory.objects.filter(id=product['category']).exists():
                logger.error(f"{product['title']} - Category ID {product['category']} not exist!")
                continue
            
            # Get Category of Product
            category = MyRogaCategory.objects.get(id=product['category'])

            # Check Technical aspect is Valid or not
            aspect_params = {
                    'product': product,
                    'TECHNICAL_ASPECTS_VALID_COLUMNS': TECHNICAL_ASPECTS_VALID_COLUMNS,
                    'category': category
                }

            isAspectsValid = self.check_valid_product_technical_aspect(**aspect_params)
            if not isAspectsValid:
                logger.error(f"{product['title']} - Technical Aspects not valid!")
                continue
            
            # Get Language of Product
            try:
                language = Language.objects.filter(name__iexact=product['language']).first()
            except:
                logger.error("Language not available or not have a column in uploaded file!")
                language = None

            hero_offer_market_place = None
            if 'hero offer marketplace id' in product.keys() and product['hero offer marketplace id']:
                hero_offer_market_place = MarketPlace.objects.filter(id=int(product['hero offer marketplace id'])).first()

            second_offer_market_place = None
            if 'second offer marketplace id' in product.keys() and product['second offer marketplace id']:
                second_offer_market_place = MarketPlace.objects.filter(id=int(product['second offer marketplace id'])).first()

            request_params = {
                'title': product['title'] if 'title' in product.keys() else '',
                'description': product['description'] if 'description' in product.keys() else '',
                'my_roga_category': category,
                'language': language,
                'hero_offer': None,
                'second_offer': None,
                'image_url': product['image url'] if 'image url' in product.keys() else '',
                'review_url': product['review url'] if 'review url' in product.keys() else '',
                'review_count': product['reviews count'] if 'reviews count' in product.keys() and product['reviews count'] else 0,
                'review_score': product['reviews score'] if 'reviews score' in product.keys() and product['reviews score'] else 0,
                'hero_offer_url': product['hero offer url'] if 'hero offer url' in product.keys() and product['hero offer url'] else '',

my_roga/templates/product/aggregation_model_set.html
{% extends 'index.html' %}

{% block content %}

<div>
    <div class="row">
        <div class="row col-lg-12 col-md-12 col-sm-12">
            <form action="{% url 'product:upload_aggregation_model_set' %}" method="POST" enctype="multipart/form-data" class="row col-lg-8 col-md-8 col-sm-8"> 
                {% csrf_token %}
                <div class="col-lg-8 col-md-8 col-sm-8">
                    <label for="inputState">Upload Aggregation Model Set(xls, xlsx):</label>
                    <input type="file" name="upload_file" id="upload_file" required="True" class="form-control">
                    {% if error %}
                        <span class="error">{{ message }}</span>
                    {% endif %}
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 m-t-32">
                    <button class="btn btn-success">
                        <i class="fa fa-upload" aria-hidden="true"></i>&nbsp;
                        Upload
                    </button>
                </div>
            </form>
        </div>
    </div>
    <br /><br />
    <div class="row">
        <div class="row col-lg-12 col-md-12 col-sm-12">
            <form action="{% url 'product:upload_aggregation_model_set' %}" method="GET" class="row col-lg-6 col-md-6 col-sm-6"> 
                <div class="col-lg-10 col-md-10 col-sm-10">
                    <label for="inputState">Select Category</label>
                    <select id="inputState" class="form-control" name="category">
                        <option value=""
                            {% if selected_category == "" %}selected="selected"{% endif %}>
                            Select Category
                        </option>
                        {% for category in categories %}
                            <option value="{{category.id}}"
                                {% if category == selected_category %}selected="selected"{% endif %}>
                                {{ category.id }} - {{ category.name }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-2 m-t-32">
                    <button class="btn btn-success">
                        Submit
                    </button>
                </div>
            </form>
            <div class="col-lg-6 col-md-6 col-sm-6 m-t-32">
                <a href="{% url 'product:upload_aggregation_model_set' %}">
                    <button class="btn btn-primary">
                        Reset
                    </button>
                </a>
            </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div>
                <div class="current_status m-t-15">
                    <div class="download-button">
                        <a href="{% url 'product:download_aggregation_model_set' %}?category_id={{selected_category.id}}">
                            <button class="btn btn-warning"
                                {% if not records %} disabled {%endif%}>
                                <i class="fa fa-download" aria-hidden="true"></i>&nbsp;
                                Download Product Aspect
                            </button>
                        </a>
                    </div>
                    <div>
                        <table class="table table-bordered">
                            <thead class="thead-dark">
                                <tr>
                                    <th class="text-center">ID</th>
                                    <th class="text-center">Category</th>
                                    <th class="text-center">Aspects</th>
                                    <th class="text-center">Updated At</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if records %}
                                    {% for record in records %}
                                        <tr>
                                            <td class="text-center">{{record.id}}</td>
                                            <td class="text-center">{{record.my_roga_category.name}}</td>
                                            <td class="text-center">{{record.aspects}}</td>
                                            <td class="text-center">{{record.updated_at}}</td>
                                        </tr>
                                    {% endfor %}
                                {% else %}
                                    <tr>
                                        <td colspan="7">No Data Available</td>
                                    </tr>
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

my_roga/templates/product/aspects.html
{% extends 'index.html' %}

{% block content %}

<div>
    <div class="row">
        <div class="row col-lg-12 col-md-12 col-sm-12">
            <form action="{% url 'product:upload_product_aspects' %}" method="POST" enctype="multipart/form-data" class="row col-lg-8 col-md-8 col-sm-8"> 
                {% csrf_token %}
                <div class="col-lg-8 col-md-8 col-sm-8">
                    <label for="inputState">Upload Product Aspects(xls, xlsx):</label>
                    <input type="file" name="upload_file" id="upload_file" required="True" class="form-control">
                    {% if error %}
                        <span class="error">{{ message }}</span>
                    {% endif %}
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 m-t-32">
                    <button class="btn btn-success">
                        <i class="fa fa-upload" aria-hidden="true"></i>&nbsp;
                        Upload
                    </button>
                </div>
            </form>
        </div>
    </div>
    <br /><br />
    <div class="row">
        <div class="row col-lg-12 col-md-12 col-sm-12">
            <form action="{% url 'product:upload_product_aspects' %}" method="GET" class="row col-lg-6 col-md-6 col-sm-6"> 
                <div class="col-lg-10 col-md-10 col-sm-10">
                    <label for="inputState">Select Category</label>
                    <select id="inputState" class="form-control" name="category">
                        <option value=""
                            {% if selected_category == "" %}selected="selected"{% endif %}>
                            Select Category
                        </option>
                        {% for category in categories %}
                            <option value="{{category.id}}"
                                {% if category == selected_category %}selected="selected"{% endif %}>
                                {{ category.id }} - {{ category.name }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-2 m-t-32">
                    <button class="btn btn-success">
                        Submit
                    </button>
                </div>
            </form>
            <div class="col-lg-6 col-md-6 col-sm-6 m-t-32">
                <a href="{% url 'product:upload_product_aspects' %}">
                    <button class="btn btn-primary">
                        Reset
                    </button>
                </a>
            </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div>
                <div class="current_status m-t-15">
                    <div class="download-button">
                        <a href="{% url 'product:download_product_aspects' %}?category_id={{selected_category.id}}">
                            <button class="btn btn-warning"
                                {% if not records %} disabled {%endif%}>
                                <i class="fa fa-download" aria-hidden="true"></i>&nbsp;
                                Download Product Aspect
                            </button>
                        </a>
                    </div>
                    <div>
                        <table class="table table-bordered">
                            <thead class="thead-dark">
                                <tr>
                                    <th class="text-center">ID</th>
                                    <th class="text-center">AspectName</th>
                                    <th class="text-center">Category</th>
                                    <th class="text-center">Aspect MetaData Type</th>
                                    <th class="text-center">Aspect MetaData Input Type</th>
                                    <th class="text-center">Is Model Aspect</th>
                                    <th class="text-center">Model Title Order</th>
                                    <th class="text-center">Model Title Text Before Aspect</th>
                                    <th class="text-center">Model Title Text After Aspect</th>
                                    <th class="text-center">Updated At</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if records %}
                                    {% for record in records %}
                                        <tr>
                                            <td class="text-center">{{record.id}}</td>
                                            <td class="text-center">{{record.name}}</td>
                                            <td class="text-center">{{record.my_roga_category.name}}</td>
                                            <td class="text-center">{{record.aspect_type}}</td>
                                            <td class="text-center">{{record.aspect_input_type}}</td>
                                            <td class="text-center">{{record.is_model_aspect}}</td>
                                            <td class="text-center">{{record.model_title_order}}</td>
                                            <td class="text-center">{{record.model_title_text_before_aspect}}</td>
                                            <td class="text-center">{{record.model_title_text_after_aspect}}</td>
                                            <td class="text-center">{{record.updated_at}}</td>
                                        </tr>
                                    {% endfor %}
                                {% else %}
                                    <tr>
                                        <td colspan="11">No Data Available</td>
                                    </tr>
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

my_roga/templates/product/product.html
{% extends 'index.html' %}
{% load dict_key_with_spaces %}

{% block content %}

<div>
    <div class="row">
        <div class="row col-lg-12 col-md-12 col-sm-12">
            <form action="{% url 'product:upload_product' %}" method="POST"
                enctype="multipart/form-data" class="row col-lg-8 col-md-8 col-sm-8"> 
                {% csrf_token %}
                <div class="col-lg-8 col-md-8 col-sm-8">
                    <label for="inputState">Upload Product (xls, xlsx):</label>
                    <input type="file" name="upload_file" id="upload_file" required="True" class="form-control">
                    {% if error %}
                        <span class="error">{{ message }}</span>
                    {% endif %}
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 m-t-32">
                    <button class="btn btn-success">
                        <i class="fa fa-upload" aria-hidden="true"></i>&nbsp;
                        Upload
                    </button>
                </div>
            </form>
        </div>
    </div>
    <br /><br />
    <div class="row">
        <div class="row col-lg-12 col-md-12 col-sm-12 m-b-1">
            <form action="{% url 'product:upload_product' %}" method="GET" class="row col-lg-10 col-md-10 col-sm-12"> 
                <div class="col-lg-5 col-md-5 col-sm-12">
                    <label for="inputState">Select Category</label>
                    <select id="inputState" class="form-control" name="category">
                        <option value=""
                            {% if selected_category == "" %}selected="selected"{% endif %}>
                            Select Category
                        </option>
                        {% for category in categories %}
                            <option value="{{category.id}}"
                                {% if category == selected_category %}selected="selected"{% endif %}>
                                {{ category.id }} - {{ category.name }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-lg-5 col-md-5 col-sm-12">
                    <label for="inputState">Select Product</label>
                    <select id="inputState" class="form-control" name="product">
                        <option value=""
                            {% if selected_product == "" %}selected="selected"{% endif %}>
                            Select Product
                        </option>
                        {% for product in products %}
                            <option value="{{product.id}}"
                                {% if product == selected_product %}selected="selected"{% endif %}>
                                {{ product.id }} - {{ product.title }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-12 m-t-32">
                    <button class="btn btn-success">
                        Submit
                    </button>
                </div>
            </form>
            <div class="col-lg-2 col-md-2 col-sm-2 m-t-32 ml-4">
                <a href="{% url 'product:upload_product' %}">
                    <button class="btn btn-primary">
                        Reset
                    </button>
                </a>
            </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div>
                <div class="current_status m-t-15">
                    <div class="download-button">
                        <a href="{% url 'product:download_products' %}?category={{selected_category.id}}&product={{selected_product.id}}">
                            <button class="btn btn-warning"
                                {% if not records %} disabled {%endif%}>
                                <i class="fa fa-download" aria-hidden="true"></i>&nbsp;
                                Download Products
                            </button>
                        </a>
                    </div>
                    <div class="table-width">
                        <table class="table table-bordered">
                            <thead class="thead-dark">
                                <tr>
                                    {% for column in columns %}
                                        <th class="text-center">{{column}}</th>
                                    {% endfor %}
                                </tr>
                            </thead>
                            <tbody>
                                {% if records %}
                                    {% for record in records %}
                                        <tr>
                                            {% for column in columns %}
                                                <td class="text-center">{{record|dict_with_space:column}}</td>
                                            {% endfor %}
                                        </tr>
                                    {% endfor %}
                                {% else %}
                                    <tr>
                                        <td colspan="{{columns|length}}">No Data Available</td>
                                    </tr>
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}