apps/model_catalog/urls.py
from django.urls import path
from model_catalog.views import ManageModelCatalog, ExportModelCatalog, \
    FetchModelCatalogProducts, ReprocessModelCatalog

app_name = 'model_catalog'

urlpatterns = [
    path('', ManageModelCatalog.as_view(), name="model_catalog_home"),
    path('download/', ExportModelCatalog.as_view(), name="download_model_catalog"),
    path('<int:id>/products/', FetchModelCatalogProducts.as_view(), name="model_catalog_products"),
    path('reprocess-model-catalog/<int:category_id>/', ReprocessModelCatalog.as_view(), name="reprocess_model_catalog"),
]

my_roga/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from my_roga import settings

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('', include(('home.urls'), namespace='home')),
    path('auth/', include(('authentication.urls'), namespace='authentication')),
    path('model-catalog/', include(('model_catalog.urls'), namespace='model_catalog')),
    path('product/', include(('product.urls'), namespace='product')),
    path('quiz/', include(('quiz.urls'), namespace='quiz')),
    path('admin/', admin.site.urls),
]

apps/model_catalog/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from my_roga.models import ActivityTracking
from my_roga.managers import ActivityQuerySet


class ModelCatalog(ActivityTracking):
    MODEL_STATUS = (
        ('1', _('Live')),
        ('2', _('Deleted')),
    )

    product_catalog = models.ManyToManyField('product.ProductCatalog',
                related_name='model_catalog_products')
    aggregation_model_set= models.ForeignKey('product.AggregationModelSet',
                related_name='aggregation_model_catalog',
                on_delete=models.CASCADE)
    model_aggregation_key = models.TextField(help_text=_('Model Aggregation Key'),
                verbose_name=_('Model Aggregation Key'))
    my_roga_category = models.ForeignKey('home.MyRogaCategory',
                related_name='model_catalog_my_roga_category',
                null=True,
                on_delete=models.SET_NULL)
    language = models.ForeignKey('home.Language',
                related_name='model_catalog_language',
                null=True,
                on_delete=models.SET_NULL)

    # Not in Use until Offer Table Created
    hero_offer = models.ForeignKey('offer.Offer',
                related_name='model_catalog_hero_offer',
                null=True,
                on_delete=models.SET_NULL)
    second_offer = models.ForeignKey('offer.Offer',
                related_name='model_catalog_second_offer',
                null=True,
                on_delete=models.SET_NULL)

    # For now we will use this Product Catalog id for Hero Product
    # After that we will use the Offer Table id
    hero_product = models.ForeignKey('product.ProductCatalog',
                related_name='model_catalog_hero_product',
                null=True,
                on_delete=models.SET_NULL)
    hero_product_price = models.FloatField(max_length=11,
                null=True, blank=True, default=0,
                help_text=_('Hero Product Price'),
                verbose_name=_('Hero Product Price'))
    hero_product_market_place = models.ForeignKey('home.MarketPlace',
                related_name='hero_product_market_place',
                null=True,
                on_delete=models.SET_NULL)
    second_hero_product = models.ForeignKey('product.ProductCatalog',
                related_name='model_catalog_second_hero_product',
                null=True,
                on_delete=models.SET_NULL)
    second_hero_product_price = models.FloatField(max_length=11,
                null=True, blank=True, default=0,
                help_text=_('Second Hero Product Price'),
                verbose_name=_('Second Hero Product Price'))
    second_hero_product_market_place = models.ForeignKey('home.MarketPlace',
                related_name='second_hero_product_market_place',
                null=True,
                on_delete=models.SET_NULL)

    title = models.CharField(max_length=255,
                help_text=_('Model title'), 
                verbose_name=_('Model title'))
    description = models.TextField(blank=True, null=True,
                help_text=_('Model Description'),
                verbose_name=_('Model Description'))
    description_image_url = models.TextField(blank=True, null=True,
                help_text=_('Model Description Image URL'),
                verbose_name=_('Model Description Image URL'))
    model_status = models.CharField(max_length=128,
                choices=MODEL_STATUS,
                help_text=_('Model Status'),
                verbose_name=_('Model Status'),
                null=True, blank=True)
    model_stealth = models.CharField(max_length=50,
                null=True, blank=True,
                help_text=_('Model Stealth'),
                verbose_name=_('Model Stealth'))
    product_review_count = models.IntegerField(null=True, blank=True, default=0,
                help_text=_('Product Review Count'), 
                verbose_name=_('Product Review Count'))
    product_review_score = models.FloatField(max_length=11,
                null=True, blank=True, default=0,
                help_text=_('Product Review Score'),
                verbose_name=_('Product Review Score'))
    image_url = models.TextField(blank=True, null=True,
                help_text=_('Model Image URL'),
                verbose_name=_('Model Image URL'))
    review_url = models.TextField(blank=True, null=True,
                help_text=_('Review URL'),
                verbose_name=_('Review URL'))
    recommendation_score = models.FloatField(max_length=11,
                null=True, blank=True, default=0,
                help_text=_('Recommendation Score'),
                verbose_name=_('Recommendation Score'))
    
    objects = ActivityQuerySet.as_manager()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Model Catalog")
        verbose_name_plural = _("Model Catalog")
        ordering = ['-created_at']

my_roga/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class ActivityTracking(models.Model):
    active = models.BooleanField(verbose_name=_('Active'), default=True)
    is_deleted = models.BooleanField(verbose_name=_('Is Deleted'), default=False)
    created_at = models.DateTimeField(verbose_name=_('Created At'),
                    auto_now_add=True, help_text=_("Date when created."), null=True)
    updated_at = models.DateTimeField(verbose_name=_('Updated At'),
                    auto_now=True, help_text=_("Date when updated."), null=True)
    deleted_at = models.DateTimeField(verbose_name=_('Deleted At'),
                    default=None, null=True, blank=True, help_text=_("Date when deleted"))
    delete_reason = models.CharField(max_length=300, verbose_name=_('Delete Reason'),
                    default=None, null=True, blank=True, help_text=_("Delete Reason"))

    class Meta:
        abstract = True

apps/model_catalog/views.py
import logging
import copy
import numpy as np
from django.utils import timezone
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views import View
from openpyxl import Workbook
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin

from rest_framework.views import APIView
from rest_framework.response import Response

from product.models import ProductCatalog, AspectsMetaData, AspectValuesMetaData, \
    AggregationModelSet
from model_catalog.models import ModelCatalog
from home.models import MyRogaCategory, Language, MarketPlace
from my_roga.common.utils import read_file, VALID_FILE_EXTENSION, MODULES_NAME
from my_roga.common.actions import Actions
from my_roga.common.logs import LogAction
from model_catalog.common import get_formatted_model_catalogs
from product.common import get_model_catalog_formatted_products


logger = logging.getLogger(__name__)


class ManageModelCatalog(LoginRequiredMixin, View):
    template_name = "model_catalog/model_catalog.html"

    def get(self, request):
        selected_category = request.GET['category'] if 'category' in request.GET else None
        categories = MyRogaCategory.objects.isNotDeleted()

        if selected_category:
            records = ModelCatalog.objects.isNotDeleted().filter(my_roga_category__id=selected_category)
            selected_category = categories.filter(id=selected_category).first()
        else:
            records = ModelCatalog.objects.isNotDeleted()
            selected_category = ""
        
        selected_category_id = selected_category.id if selected_category else ""
        response = get_formatted_model_catalogs(records, selected_category_id)
        results = response['results']
        columns = response['COLUMNS']
        return render(request, template_name=self.template_name, context={
            "error": False,
            "message": "Model Catalog fetched Successfully!",
            "records": results,
            "categories": categories,
            "columns": columns,
            "selected_category": selected_category,
        })

    def post(self, request):
        VALID_COLUMNS = ['action', 'model catalog id', 'model stealth', \
            'model status', 'model description', 'model description image url', \
            'model image url', 'recommendation score']
        upload_file = request.FILES.get("upload_file")
        file_extension = upload_file.name.split(".")[1]
        isAllColumnsValid = True

        # Check valid file extension
        if file_extension not in VALID_FILE_EXTENSION:
            logger.error("Please Upload file with only xls, xlsx & csv extension!")
            return render(request, template_name=self.template_name, context={
                "error": True,
                "message": "Please Upload file with only xls, xlsx & csv extension!"
            })
        
        # Read the uploaded file
        try:
            model_catalog = read_file(upload_file)
        except Exception as e:
            logger.error(f"File not valid or does not have valid data! - {e.message}")
            return render(request, template_name=self.template_name, context={
                "error": True,
                "message": "File not valid or does not have valid data!"
            })
        
        # Uploaded file column names
        file_columns =  list(map(lambda x:x.lower(), list(model_catalog.columns)))

        for column in file_columns:
            if column not in VALID_COLUMNS:
                isAllColumnsValid = False
                break
        
        if not isAllColumnsValid:
            logger.error("Uploaded file does not have valid column names!")
            return render(request, template_name=self.template_name, context={
                "error": True,
                "message": "Uploaded file does not have valid column names!"
            })
        
        model_catalog.columns = file_columns
        model_catalog = model_catalog.replace(np.nan, '', regex=True)
        model_catalog = model_catalog.to_dict('records')

        # Create Model Catalog object and store it into database
        for item in model_catalog:
            model_catalog_id = item['model catalog id']
            # Check If Model Catalog Id is valid or not
            if not model_catalog_id:
                logger.error(f"Model Catalog ID {model_catalog_id} is not valid or available in column!")
            
            model_catalog_action = item['action'].upper()

            # Get Model Catalog Object
            model_catalog_object = ModelCatalog.objects.filter(id=model_catalog_id).first()
            if not model_catalog_object:
                logger.error(f"{model_catalog_action} - Model Catalog with ID {model_catalog_id} is not available!")
            
            
            # Handle Model Catalog operations.
            if model_catalog_action == 'UPDATE':
                # Check Model Status value
                model_status = item['model status']
                if model_status.lower() == 'live':
                    model_status = '1'
                elif model_status.lower() == 'delete' or model_status.lower() == 'deleted':
                    model_status = '2'
                else:
                    model_status = ''
                # Request params for Update
                request_params = {
                    'model_stealth': item['model stealth'] if item['model stealth'] else '',
                    'model_status': model_status,
                    'description': item['model description'],
                    'description_image_url': item['model description image url'],
                    'image_url': item['model image url'],
                    'recommendation_score': item['recommendation score'] if item['recommendation score'] else 0,
                }
                Actions(ModelCatalog).update(model_catalog_id, **request_params)
            elif model_catalog_action == 'DELETE':
                delete_reason = 'Manual deletion'
                Actions(ModelCatalog).soft_delete(model_catalog_id, delete_reason)
            elif model_catalog_action == 'REVIVE':
                Actions(ModelCatalog).revive(model_catalog_id)
            else:
                logger.error(f"{model_catalog_action} Model Catalog Action not valid!")
        return redirect('/model-catalog/')


class ExportModelCatalog(LoginRequiredMixin, View):

    def get(self, request):
        """
        Downloads all Model Catalog as Excel file with a single worksheet
        """
        category_id = request.GET['category'] if 'category' in request.GET else None
        if category_id:
            model_catalog = ModelCatalog.objects.isNotDeleted().filter(my_roga_category=category_id)
        else:
            model_catalog = ModelCatalog.objects.isNotDeleted()
        
        response = HttpResponse(
            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        )
        response['Content-Disposition'] = 'attachment; filename={date}-model_catalog.xlsx'.format(
            date=timezone.now().strftime('%Y-%m-%d'),
        )
        workbook = Workbook()
        
        # Get active worksheet/tab
        worksheet = workbook.active
        worksheet.title = 'Model Catalog'

        # Define the titles for columns
        columns = [
            'ID',
            'Model Title',
            'MyRogaCategoryID',
            'Aggregation Key',
            'Language',
            'Model Stealth',
            'Model Status',
            'Model Description',
            'Model Description Image URL',
            'Model Image URL',
            'Hero Product',
            'Hero Product Price',
            'Hero Product Market Place',
            'Second Hero Product',
            'Second Hero Product Price',
            'Second Hero Product Market Place',
            'Product Review Count',
            'Product Review Score',
            'Review URL',
            'Recommendation Score',
        ]
        row_num = 1

        # get formatted model catalog results
        response_results = get_formatted_model_catalogs(model_catalog, category_id)
        results = response_results['results']
        aspect_columns = response_results['COLUMNS']

        for column in aspect_columns:
            columns.append(column)

        columns.append('Updated At')

        # Assign the titles for each cell of the header
        for col_num, column_title in enumerate(columns, 1):
            cell = worksheet.cell(row=row_num, column=col_num)
            cell.value = column_title

        # Iterate through all model catalog
        for model in results:
            row_num += 1
            
            # Define the data for each cell in the row 
            row = [
                model['id'],
                model['title'],
                model['my_roga_category'].id,
                model['aggregation_key'],
                model['language'],
                model['model_stealth'],
                model['model_status'],
                model['description'],
                model['description_image_url'],
                model['image_url'],
                model['hero_product'],
                model['hero_product_price'],
                model['hero_product_market_place'],
                model['second_hero_product'],
                model['second_hero_product_price'],
                model['second_hero_product_market_place'],
                model['product_review_count'],
                model['product_review_score'],
                model['review_url'],
                model['recommendation_score'],
            ]

            for col in aspect_columns:
                row.append(model[col])

            row.append(model['updated_at'])
            
            # Assign the data for each cell of the row 
            for col_num, cell_value in enumerate(row, 1):

my_roga/templates/model_catalog/model_catalog.html
{% extends 'index.html' %}
{% load dict_key_with_spaces %}

{% load static %}
{% block content %}

<div>
    <div class="row">
        <div class="row col-lg-12 col-md-12 col-sm-12">
            <form action="{% url 'model_catalog:model_catalog_home' %}" method="POST" enctype="multipart/form-data" class="row col-lg-8 col-md-8 col-sm-8"> 
                {% csrf_token %}
                <div class="col-lg-8 col-md-8 col-sm-8">
                    <label for="inputState">Upload Model Catalog(xls, xlsx):</label>
                    <input type="file" name="upload_file" id="upload_file" required="True" class="form-control">
                    {% if error %}
                        <span class="error">{{ message }}</span>
                    {% endif %}
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 m-t-32">
                    <button class="btn btn-success">
                        <i class="fa fa-upload" aria-hidden="true"></i>&nbsp;
                        Upload
                    </button>
                </div>
            </form>
        </div>
    </div>
    <br /><br />
    <div class="row">
        <div class="row col-lg-12 col-md-12 col-sm-12">
            <form action="{% url 'model_catalog:model_catalog_home' %}" method="GET" class="row col-lg-6 col-md-6 col-sm-6"> 
                <div class="col-lg-10 col-md-10 col-sm-10">
                    <label for="inputState">Select Category</label>
                    <select id="inputState" class="form-control" name="category">
                        <option value=""
                            {% if selected_category == "" %}selected="selected"{% endif %}>
                            Select Category
                        </option>
                        {% for category in categories %}
                            <option value="{{category.id}}"
                                {% if category == selected_category %}selected="selected"{% endif %}>
                                {{ category.id }} - {{ category.name }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-2 m-t-32">
                    <button class="btn btn-success">
                        Submit
                    </button>
                </div>
            </form>
            <div class="col-lg-6 col-md-6 col-sm-6 m-t-32">
                <a href="{% url 'model_catalog:model_catalog_home' %}">
                    <button class="btn btn-primary">
                        Reset
                    </button>
                </a>
            </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div>
                <div class="current_status m-t-15">
                    <div class="download-button">
                        <button class="btn btn-info" data-toggle="modal" onclick="openReprocessModal()">
                            Reprocess
                        </button>
                        <a href="{% url 'model_catalog:download_model_catalog' %}?category={{selected_category.id}}">
                            <button class="btn btn-warning"
                                {% if not records %} disabled {%endif%}>
                                <i class="fa fa-download" aria-hidden="true"></i>&nbsp;
                                Download Model Catalog
                            </button>
                        </a>
                    </div>
                    <div class="table-width">
                        <table class="table table-bordered display nowrap" id="model_catalog_table">
                            <thead class="thead-dark">
                                <tr>
                                    <th class="width-10"></th>
                                    <th class="text-center">ID</th>
                                    <th class="text-center">Title</th>
                                    <th class="text-center">Category</th>
                                    <th class="text-center">Aggregation Key</th>
                                    <th class="text-center">Language</th>
                                    <th class="text-center">Model Stealth</th>
                                    <th class="text-center">Model Status</th>
                                    <th class="text-center">Model Description</th>
                                    <th class="text-center">Model Description Image URL</th>
                                    <th class="text-center">Model Image URL</th>
                                    <th class="text-center">Hero Product</th>
                                    <th class="text-center">Hero Product Price</th>
                                    <th class="text-center">Hero Product Market Place</th>
                                    <th class="text-center">Second Hero Product</th>
                                    <th class="text-center">Second Hero Product Price</th>
                                    <th class="text-center">Second Hero Product Market Place</th>
                                    <th class="text-center">Product Review Count</th>
                                    <th class="text-center">Product Review Score</th>
                                    <th class="text-center">Review URL</th>
                                    <th class="text-center">Recommendation Score</th>
                                    {% for column in columns %}
                                        <th class="text-center">{{column}}</th>
                                    {% endfor %}
                                    <th class="text-center">Updated At</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if records %}
                                    {% for record in records %}
                                        <tr>
                                            <td class="details-control width-10"></td>
                                            <td class="text-center">{{record.id}}</td>
                                            <td class="text-center">{{record.title}}</td>
                                            <td class="text-center">{{record.my_roga_category.name}}</td>
                                            <td class="text-center">{{record.aggregation_key}}</td>
                                            <td class="text-center">{{record.language}}</td>
                                            <td class="text-center">{{record.model_stealth}}</td>
                                            <td class="text-center">{{record.model_status}}</td>
                                            <td class="text-center">{{record.description}}</td>
                                            <td class="text-center">{{record.description_image_url}}</td>
                                            <td class="text-center">{{record.image_url}}</td>
                                            <td class="text-center">{{record.hero_product}}</td>
                                            <td class="text-center">{{record.hero_product_price}}</td>
                                            <td class="text-center">{{record.hero_product_market_place}}</td>
                                            <td class="text-center">{{record.second_hero_product}}</td>
                                            <td class="text-center">{{record.second_hero_product_price}}</td>
                                            <td class="text-center">{{record.second_hero_product_market_place}}</td>
                                            <td class="text-center">{{record.product_review_count}}</td>
                                            <td class="text-center">{{record.product_review_score}}</td>
                                            <td class="text-center">{{record.review_url}}</td>
                                            <td class="text-center">{{record.recommendation_score}}</td>
                                            {% for column in columns %}
                                                <td class="text-center">{{record|dict_with_space:column}}</td>
                                            {% endfor %}
                                            <td class="text-center">{{record.updated_at}}</td>
                                        </tr>
                                    {% endfor %}
                                {% else %}
                                    <tr>
                                        <td colspan="23">No Data Available</td>
                                    </tr>
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- Reprocess Model -->
            <div class="modal fade" id="reprocessModel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Confirm Reprocess Changes</h5>
                                <button type="button" class="close" onclick="closeReprocessModal()" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <input type="hidden" name="reprocess_selected_category" value="{{selected_category.id}}"/>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" onclick="closeReprocessModal()">Close</button>
                            <button type="button" class="btn btn-primary">Apply</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}