apps/home/urls.py
from django.urls import path
from home.views import HomeView, UploadCategory, ExportCategoryToXlsx, \
    LogView

app_name = 'home'
urlpatterns = [
    path('', HomeView.as_view(), name='home-view'),
    path('category-upload/', UploadCategory.as_view(), name='upload_category'),
    path('download-category/', ExportCategoryToXlsx.as_view(), name='download_categories'),
    path('logs/', LogView.as_view(), name='logs')
]

my_roga/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from my_roga import settings

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('', include(('home.urls'), namespace='home')),
    path('auth/', include(('authentication.urls'), namespace='authentication')),
    path('model-catalog/', include(('model_catalog.urls'), namespace='model_catalog')),
    path('product/', include(('product.urls'), namespace='product')),
    path('quiz/', include(('quiz.urls'), namespace='quiz')),
    path('admin/', admin.site.urls),
]

apps/home/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from my_roga.models import ActivityTracking
from my_roga.managers import ActivityQuerySet


class Language(ActivityTracking):
    name = models.CharField(max_length=50, unique=True,
                help_text=_('Language name'), 
                verbose_name=_('Language name'))
    
    objects = ActivityQuerySet.as_manager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Language")
        verbose_name_plural = _("Languages")
        ordering = ['-created_at']


class MyRogaCategory(ActivityTracking):
    name = models.CharField(max_length=56, unique=True,
                help_text=_('Category name'), 
                verbose_name=_('Category name'))
    description = models.TextField(blank=True, null=True, 
                help_text=_('Category Description'),
                verbose_name=_('Category Description'))

    objects = ActivityQuerySet.as_manager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("MyRoga Category")
        verbose_name_plural = _("MyRoga Categories")
        ordering = ['-created_at']


class MarketPlace(ActivityTracking):
    name = models.CharField(max_length=56, unique=True,
                help_text=_('Market place name'), 
                verbose_name=_('Market place name'))
    
    objects = ActivityQuerySet.as_manager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Market Place")
        verbose_name_plural = _("Market Places")
        ordering = ['-created_at']


class MarketPlaceCategory(ActivityTracking):
    market_place = models.ForeignKey('home.MarketPlace',
                related_name='market_place',
                on_delete=models.CASCADE)
    name = models.CharField(max_length=255, unique=True,
                help_text=_('Category name'), 
                verbose_name=_('Category name'))
    description = models.TextField(blank=True, null=True, 
                help_text=_('Category Description'),
                verbose_name=_('Category Description'))
    
    objects = ActivityQuerySet.as_manager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Market Place Category")
        verbose_name_plural = _("Market Place Categories")
        ordering = ['-created_at']


class MyRogaMarketPlaceCategory(ActivityTracking):
    my_roga_category = models.ForeignKey('home.MyRogaCategory',
                related_name='my_roga_category',
                on_delete=models.CASCADE)
    market_place_category = models.ForeignKey('home.MarketPlaceCategory',
                related_name='market_place_category',
                on_delete=models.CASCADE)
    
    objects = ActivityQuerySet.as_manager()

    def __str__(self):
        return f"{self.my_roga_category.name} - {self.market_place_category.name}"

    class Meta:
        verbose_name = _("MyRoga and Market Place Category")
        verbose_name_plural = _("MyRoga and Market Place Categories")
        ordering = ['-created_at']


class LogModule(ActivityTracking):
    name = models.CharField(max_length=56, unique=True,
                help_text=_('Module name'), 
                verbose_name=_('Module name'))
    
    objects = ActivityQuerySet.as_manager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Log Module")
        verbose_name_plural = _("Log Module")
        ordering = ['-created_at']


class Logs(ActivityTracking):
    LOG_TYPES = (
        ('DEBUG', _('DEBUG')),
        ('INFO', _('INFO')),
        ('WARNING', _('WARNING')),
        ('ERROR', _('ERROR')),
    )

    log_module = models.ForeignKey('home.LogModule',
                related_name='log_module',
                on_delete=models.CASCADE)
    log_type = models.CharField(max_length=128,
                choices=LOG_TYPES,
                help_text=_('Log Type'),
                verbose_name=_('Log Type'),
                default='Error',
                null=True, blank=True)
    message = models.TextField(blank=True, null=True,
                help_text=_('Error Message'),
                verbose_name=_('Error Message'))
    
    objects = ActivityQuerySet.as_manager()

    def __str__(self):
        return f"{self.log_module.name} - {self.log_type}"

    class Meta:
        verbose_name = _("Logs")
        verbose_name_plural = _("Logs")
        ordering = ['-created_at']

my_roga/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class ActivityTracking(models.Model):
    active = models.BooleanField(verbose_name=_('Active'), default=True)
    is_deleted = models.BooleanField(verbose_name=_('Is Deleted'), default=False)
    created_at = models.DateTimeField(verbose_name=_('Created At'),
                    auto_now_add=True, help_text=_("Date when created."), null=True)
    updated_at = models.DateTimeField(verbose_name=_('Updated At'),
                    auto_now=True, help_text=_("Date when updated."), null=True)
    deleted_at = models.DateTimeField(verbose_name=_('Deleted At'),
                    default=None, null=True, blank=True, help_text=_("Date when deleted"))
    delete_reason = models.CharField(max_length=300, verbose_name=_('Delete Reason'),
                    default=None, null=True, blank=True, help_text=_("Delete Reason"))

    class Meta:
        abstract = True

apps/home/views.py
import logging
import numpy as np
from django.views import View
from django.utils import timezone
from django.shortcuts import render, redirect
from openpyxl import Workbook
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin

from home.models import MyRogaCategory, LogModule, Logs
from my_roga.common.utils import read_file, VALID_FILE_EXTENSION
from my_roga.common.actions import Actions


logger = logging.getLogger(__name__)


class HomeView(View):
    template_name = "home/home.html"

    def get(self, request):
        return render(request, template_name=self.template_name, context={})


class UploadCategory(LoginRequiredMixin, View):
    template_name = "home/category/category.html"

    def get(self, request):
        records = MyRogaCategory.objects.isNotDeleted()
        return render(request, template_name=self.template_name, context={
            "error": False,
            "message": "Category(s) fetched Successfully!",
            "records": records
        })
    
    def post(self, request):
        VALID_COLUMNS = ['name', 'description', 'action', 'category id']
        upload_file = request.FILES.get("upload_file")
        file_extension = upload_file.name.split(".")[1]
        isAllColumnsValid = True

        # Check valid file extension
        if file_extension not in VALID_FILE_EXTENSION:
            logger.error("Please Upload file with only xls, xlsx & csv extension!")
            return render(request, template_name=self.template_name, context={
                "error": True,
                "message": "Please Upload file with only xls, xlsx & csv extension!"
            })
        
        # Read the uploaded file
        try:
            categories = read_file(upload_file)
        except Exception as e:
            logger.error(f"File not valid or does not have valid data! - {e.message}")
            return render(request, template_name=self.template_name, context={
                "error": True,
                "message": "File not valid or does not have valid data!"
            })
        
        # Uploaded file column names
        file_columns =  list(map(lambda x:x.lower(), list(categories.columns)))

        for column in file_columns:
            if column not in VALID_COLUMNS:
                isAllColumnsValid = False
                break

        if not isAllColumnsValid:
            logger.error("Uploaded file does not have valid column names!")
            return render(request, template_name=self.template_name, context={
                "error": True,
                "message": "Uploaded file does not have valid column names!"
            })

        # Replace nan to blank string
        categories.columns = file_columns
        categories = categories.replace(np.nan, '', regex=True)
        categories = categories.to_dict('records')

        # Create category object and store it into database
        for category in categories:
            request_params = {
                'name': category['name'],
                'description': category['description']
            }

            # Handle Actions
            if category['action'].upper() == 'CREATE':
                if MyRogaCategory.objects.filter(name__iexact=category['name']).exists():
                    logger.error(f"{category['name']} category already exist!")
                    continue
                Actions(MyRogaCategory).create(**request_params)
            elif category['action'].upper() == 'UPDATE':
                if category['category id']:
                    Actions(MyRogaCategory).update(category['category id'], **request_params)
                else:
                    logger.error(f"UPDATE - {category['name']} - Category ID {category['category id']} not exist!")
            elif category['action'].upper() == 'DELETE':
                if category['category id']:
                    Actions(MyRogaCategory).soft_delete(category['category id'])
                else:
                    logger.error(f"DELETE - {category['name']} - Category ID {category['category id']} not exist!")

        return redirect('/category-upload/')


class ExportCategoryToXlsx(LoginRequiredMixin, View):

    def get(self, request):
        """
        Downloads all categories as Excel file with a single worksheet
        """
        categories = MyRogaCategory.objects.isNotDeleted()
        
        response = HttpResponse(
            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        )
        response['Content-Disposition'] = 'attachment; filename={date}-categories.xlsx'.format(
            date=timezone.now().strftime('%Y-%m-%d'),
        )
        workbook = Workbook()
        
        # Get active worksheet/tab
        worksheet = workbook.active
        worksheet.title = 'Categories'

        # Define the titles for columns
        columns = [
            'ID',
            'Name',
            'Description',
            'Updated At'
        ]
        row_num = 1

        # Assign the titles for each cell of the header
        for col_num, column_title in enumerate(columns, 1):
            cell = worksheet.cell(row=row_num, column=col_num)
            cell.value = column_title

        # Iterate through all categories
        for category in categories:
            row_num += 1
            
            # Define the data for each cell in the row 
            row = [
                category.id,
                category.name,
                category.description,
                category.updated_at,
            ]
            
            # Assign the data for each cell of the row 
            for col_num, cell_value in enumerate(row, 1):
                cell = worksheet.cell(row=row_num, column=col_num)
                cell.value = cell_value

        workbook.save(response)

        return response


class LogView(LoginRequiredMixin, View):
    template_name = "home/logs/logs.html"

    def get(self, request):

        selected_module = request.GET['module'] if 'module' in request.GET else None
        modules = LogModule.objects.isNotDeleted()
        if selected_module:
            records = Logs.objects.isNotDeleted().filter(log_module__id=selected_module)
            selected_module = modules.filter(id=selected_module).first()
        else:
            records = Logs.objects.isNotDeleted()
            selected_module = ""

        return render(request, template_name=self.template_name, context={
            "error": False,
            "message": "Category(s) fetched Successfully!",
            "records": records,
            "modules": modules,
        })

my_roga/templates/home/category/category.html
{% extends 'index.html' %}
{% load static %}

{% block content %}

<div>
    <div class="row">
        <div class="row col-lg-12 col-md-12 col-sm-12">
            <form action="{% url 'home:upload_category' %}" method="POST"
                enctype="multipart/form-data" class="row col-lg-8 col-md-8 col-sm-8"> 
                {% csrf_token %}
                <div class="col-lg-8 col-md-8 col-sm-8">
                    <label for="inputState">Upload Category(xls, xlsx):</label>
                    <input type="file" name="upload_file" id="upload_file" required="True" class="form-control">
                    {% if error %}
                        <span class="error">{{ message }}</span>
                    {% endif %}
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 m-t-32">
                    <button class="btn btn-success">
                        <i class="fa fa-upload" aria-hidden="true"></i>&nbsp;
                        Upload
                    </button>
                </div>
            </form>
        </div>
    </div>
    <br /><br />
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div>
                <div class="current_status m-t-15">
                    <div class="download-button">
                        <a href="{% url 'home:download_categories' %}">
                            <button class="btn btn-warning"
                                {% if not records %} disabled {%endif%}>
                                <i class="fa fa-download" aria-hidden="true"></i>&nbsp;
                                Download Categories
                            </button>
                        </a>
                    </div>
                    <div>
                        <table class="table table-bordered">
                            <thead class="thead-dark">
                                <tr>
                                    <th class="text-center">ID</th>
                                    <th class="text-center">Name</th>
                                    <th class="text-center">Description</th>
                                    <th class="text-center">Updated At</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if records %}
                                    {% for record in records %}
                                        <tr>
                                            <td class="text-center">{{record.id}}</td>
                                            <td class="text-center">{{record.name}}</td>
                                            <td class="text-center">{{record.description}}</td>
                                            <td class="text-center">{{record.updated_at}}</td>
                                        </tr>
                                    {% endfor %}
                                {% else %}
                                    <tr>
                                        <td colspan="4">No Data Available</td>
                                    </tr>
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}